<main class="content">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="font-weight-bold">
                            Detalhes
                        </h4>
                        <br>
                        <p>
                            <b>Status:</b> <?= \app\libs\tickets\Ticket::STATUS[$this->data['ticket']->status - 1] ?>
                            <br>
                            <b>Última atualização em:</b> <br>
                            <?php

                            $count = count($this->data['messages']);

                            echo date("d/m/Y à\s H:i", strtotime($this->data['messages'][$count - 1]->createdAt));
                            ?>
                        </p>
                        <?php if($this->data['ticket']->status != 3): ?>
                        <button class="btn btn-danger btn-block close-ticket" id="<?= $this->data['ticket']->id ?>">Fechar ticket</button>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h4 class="font-weight-bold">
                            <?= $this->data['ticket']->subject ?>
                        </h4>
                        <br>
                        <div class="p-4 chat-height" style="background: rgba(0, 0, 0, 0.03); border-radius: 8px">
                            <div class="row">
                                <?php foreach ($this->data['messages'] as $message): ?>
                                <div class="col-md-7  <?= $message->sender == 'CLIENT' ? 'ml-auto' : '' ?> pb-3">
                                    <div class="bubble-chat <?= $message->sender == 'CLIENT' ? 'customer' : '' ?>">
                                        <?= $message->message ?>
                                    </div>
                                    <p class="font-weight-light text-muted font-12 mt-2 <?= $message->sender == 'CLIENT' ? 'float-right' : '' ?>"><?= date('d/m/Y à\s H:i', strtotime($message->createdAt)) ?> - <?= $message->sender == 'CLIENT' ? 'Você' : 'Atendente' ?></p>
                                </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <?php if($this->data['ticket']->status != 3): ?>
                        <form class="chat-form">
                            <input type="hidden" name="id" value="<?= $this->data['ticket']->id ?>">
                            <textarea name="message"></textarea>
                            <button>Enviar</button>
                        </form>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<script>
    scripts.push(function() {
        var d = $('.chat-height');
        d.scrollTop(d.prop("scrollHeight"));

        $('.close-ticket').on('click', function() {

            var id = $(this).attr('id');

            $.ajax({
                url: `/client/tickets/actions/${id}`,
                method: 'DELETE',
                complete: function() {
                    location.reload();
                }
            })

        });

        $('.chat-form').on('submit', function(e) {
            e.preventDefault();

            var $btn = $('.chat-form button');

            $btn.html('Enviando...');

            $.ajax({
                url: '/client/tickets/actions',
                method: 'PUT',
                data: $(this).serialize(),
                dataType: 'JSON',
                complete: function (result) {
                    const {responseText: data} = result;

                    var res = JSON.parse(data);

                    if(res.success) {
                        location.reload();
                    }else{
                        alert(res.message);
                        $btn.html('Enviar');
                    }
                }
            });

            return false;
        });
    });
</script>