<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PremiumHosting - <?= $this->title ?></title>
	<link rel="icon" type="image/x-icon" href="https://i.imgur.com/AXaOGc7.png">
    <link rel="stylesheet" href="/app/templates/site/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/app/templates/site/bower_components/owl.carousel/dist/assets/owl.carousel.min.css" />
    <link rel="stylesheet" href="/app/templates/site/assets/css/styles.css">

    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <script src="https://kit.fontawesome.com/4cfd508d4f.js" crossorigin="anonymous"></script>
    <script>window.scripts = [];</script>
</head>
<body>
<main role="main">
    <?php if($this->title == 'Página inicial'): ?>
        <section class="presentation">
            <nav class="navbar navbar-expand-lg menu">
                <div class="container">
                    <a class="navbar-brand" href="/">
                        <img src="/app/templates/site/assets/images/logo.png" alt="..." height="36px">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado" aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
                        <span class="fa fa-bars text-white"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="/">Página inicial</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Hospedagem Minecraft
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="/minecraft/single">Minecraft</a>
                                    <a class="dropdown-item" href="/minecraft/bungeecord">Combo network</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/cloud">Cloud Computing</a>
                            </li>
                            <li class="nav-item client-area">
                                <a class="nav-link" href="/client">Área do Cliente</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="spacer"></div>
            <div class="container">
                <h1 class="font-weight-bold text-white">
                    Tudo que você precisa<br>
                    para hospedar seu projeto.
                </h1>
                <h5 class="mt-3 mb-4 font-weight-normal text-white">
                    Para qualuqer tipo de projeto, oferecemos soluções <br>
                    com excelentes custos benefícios. Confira!
                </h5>
            </div>
            <div class="divider">
                <img src="/app/templates/site/assets/images/wave.svg" class="img-fluid" alt="Waves">
            </div>
        </section>
    <?php else: ?>
        <section class="page-presentation <?= $this->getController() ?>-presentation">
            <div class="overlay">
                <nav class="navbar navbar-expand-lg menu">
                    <div class="container">
                        <a class="navbar-brand" href="/">
                            <img src="/app/templates/site/assets/images/logo.png" alt="..." height="36px">
                        </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado" aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
                            <span class="fa fa-bars text-white"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item">
                                    <a class="nav-link" href="/">Página inicial</a>
                                </li>
                                <li class="nav-item dropdown <?= $this->getController() == 'minecraft' ? 'active' : '' ?>">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Hospedagem Minecraft
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="/minecraft/single">Minecraft</a>
                                        <a class="dropdown-item" href="/minecraft/bungeecord">Combo network</a>
                                    </div>
                                </li>
                                <li class="nav-item <?= $this->getController() == 'cloud' ? 'active' : '' ?>">
                                    <a class="nav-link" href="/cloud">Cloud Computing</a>
                                </li>
                                <li class="nav-item client-area">
                                    <a class="nav-link" href="/client">Área do Cliente</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <div class="container">
                    <h1 class="text-white mt-5">
                        <?= $this->template['subtitle'] ?>
                    </h1>
                    <h2 class="text-white h5 mt-3 font-weight-light">
                        <?= $this->template['description'] ?>
                    </h2>
                </div>
            </div>
        </section>
    <?php endif; ?>
    <?= $this->render() ?>
</main>
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <img src="/app/templates/site/assets/images/logo.png" class="img-fluid mb-4" alt="Logo">
                <p class="text-muted">
                    PremiumHosting © 2019-2020 <br>
                    <small>Todos os direitos reservados.</small>
                </p>
            </div>
            <div class="col-md-4">
                <div class="h5 font-weight-normal text-white mb-2">Informações Legais</div>
                <div class="separator"></div>
                <ul>
                    <li><a href="/termos">Termos de serviço</a></li>
                    <li><a href="/termos">Política de Utilização Aceitável</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                <div class="h5 font-weight-normal text-white mb-2">Fale conosco</div>
                <div class="separator"></div>
                <ul>
                    <li><a href="/client/suporte">Ticket</a></li>
                    <li><a href="https://discord.gg/fwN6Sbk"  target="_blank_">Discord</a></li>
                </ul>
            </div>
            <div class="col-md-2">
                <div class="h5 font-weight-normal text-white mb-2">Área do Cliente</div>
                <div class="separator"></div>
                <ul>
                    <li><a href="/client/auth/login">Entrar</a></li>
                    <li><a href="/client/auth/register">Registrar</a></li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-5 pt-2">
                <img src="/app/templates/site/assets/images/bandeiras.png" height="22px" alt="Bandeiras">
            </div>
            <div class="col-md-7 text-md-right text-white pt-2">
                <small>Developed by <a href="https://kodesky.com/" target="_blank_" class="text-white font-weight-bold">Kodesky</a>.</small>
            </div>
        </div>
    </div>
</footer>
<script src="/app/templates/site/bower_components/jquery/dist/jquery.min.js"></script>
<script src="/app/templates/site/bower_components/popper.js/dist/umd/popper.min.js"></script>
<script src="/app/templates/site/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="/app/templates/site/bower_components/owl.carousel/dist/owl.carousel.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.all.min.js" integrity="sha256-2RS1U6UNZdLS0Bc9z2vsvV4yLIbJNKxyA4mrx5uossk=" crossorigin="anonymous"></script>
<script src="/app/templates/site/assets/js/app.js"></script>
<script>
    $(function() {
        if(scripts instanceof Array) {
            $.each(scripts, function (index, fn) {
                if(typeof fn === 'function') fn();
            });
        }
    });
</script>
</body>
</html>