<?php

$transaction = new \app\libs\financial\Transaction();
?>
<main class="content">
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h5 class="mb-4 font-weight-bold">Histórico de transaçãos</h5>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Transação</th>
                        <th scope="col">Referência</th>
                        <th scope="col">Cliente</th>
                        <th scope="col">Valor da Recarga</th>
                        <th scope="col">Data</th>
                        <th scope="col">Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    $transactions = $transaction->data();

                    if(count($transactions) == 0):
                        ?>
                        <tr>
                            <th colspan="6">Não há transações</th>
                        </tr>
                    <?php
                    endif;

                    foreach ($transactions as $data):
                        ?>
                        <tr>
                            <th scope="row"><?= $data->code ?></th>
                            <td><?= $data->reference ?></td>
                            <td><?= $data->username ?></td>
                            <td>R$ <?= number_format($data->gross_amount, 2, ',', '.') ?></td>
                            <td><?= date("d/m/Y à\s H:i", strtotime($data->date)) ?></td>
                            <td><?= $data->paid ? 'Creditado' : 'Pendente' ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>