<?php

$service = new \app\libs\services\Service();
$plan = new \app\libs\services\Plan();

$data = $service->pendings();
?>
<main class="content">
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h4 class="font-weight-bold">
                    Ativação pendentes
                </h4>
                <br>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Cliente</th>
                        <th scope="col">Plano</th>
                        <th scope="col">Data</th>
                        <th scope="col">Abrir</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($data as $item): ?>
                    <tr>
                        <th scope="row"><?= $item->id ?></th>
                        <td><?= \app\libs\customers\Profile::username($item->customer_id) ?></td>
                        <td><?= $plan->data($item->plan_id)->name ?> - <?= $plan->data($item->plan_id)->type ?></td>
                        <td><?= date("d/m/Y", strtotime($item->created_at)) ?></td>
                        <td><a href="/admin/pendentes/active/<?= $item->id ?>" class="btn btn-primary py-1 px-3">Abrir</a></td>
                    </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>