<?php

$plan = new \app\libs\services\Plan();
$data = $plan->data($this->getParams(0));
?>
<main class="content">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4">
                    <div class="card-body">
                        <h5 class="mb-4 font-weight-bold">Editar plano</h5>
                        <div class="alert alert-danger" style="display: none"></div>
                        <form id="update" class="row">
                            <input name="id" value="<?= $data->id ?>" type="hidden">
                            <div class="form-group col-md-5">
                                <label for="name">Nome</label>
                                <input name="name" id="name" value="<?= $data->name ?>" class="form-control">
                            </div>
                            <div class="form-group col-md-4">
                                <label for="price">Preço</label>
                                <input name="price" id="price" type="number" value="<?= $data->price ?>" class="form-control">
                            </div>
                            <div class="form-group col-md-3">
                                <label for="type">Categoria</label>
                                <select name="type" id="type" class="form-control" style="padding: 0 10px!important">
                                    <option value="MINECRAFT_SINGLE" <?= $data->type == 'MINECRAFT_SINGLE' ? 'selected' : '' ?>>Hospedagem Minecraft</option>
                                    <option value="MINECRAFT_BUNGEECORD" <?= $data->type == 'MINECRAFT_BUNGEECORD' ? 'selected' : '' ?>>Minecraft BungeeCord</option>
                                    <option value="CLOUD_COMPUTING" <?= $data->type == 'CLOUD_COMPUTING' ? 'selected' : '' ?>>Cloud Computing</option>
                                </select>
                            </div>
                            <div class="form-group col-md-12 pt-2">
                                <label>Características</label>
                                <button type="button" class="float-right btn btn-light btn-no-animation btn-sm" onclick="addFeature()">Adicionar</button>
                                <br><br>
                                <div id="features">
                                    <?php

                                    $i = 0;
                                    foreach (json_decode($data->data) as $feature):
                                        $i++;
                                    ?>
                                    <div class="row pt-2" id="ft-<?= $i ?>">
                                        <div class="col-md-8">
                                            <input class="form-control feature-data" name="data[]" value="<?= $feature ?>" id="feature-<?= $i ?>">
                                        </div>
                                        <div class="col-md-4">
                                            <a class="text-danger" onclick="removeFeature(<?= $i ?>)">Remover</a>
                                        </div>
                                    </div>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <button class="btn btn-warning">Salvar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<script>
    function addFeature()
    {
        var featureDiv = $('#features');
        var featureData = $('.feature-data');

        var id = featureData.length + 1;

        featureDiv.append('<div class="row pt-2" id="ft-'+id+'">\n' +
            '                                        <div class="col-md-8">\n' +
            '                                            <input class="form-control feature-data" name="data[]" id="feature-' + id + '">\n' +
            '                                        </div>\n' +
            '                                        <div class="col-md-4 pt-2">\n' +
            '                                            <a class="text-danger" onclick="removeFeature('+id+')">Remover</a>\n' +
            '                                        </div>\n' +
            '                                    </div>');
    }

    function removeFeature(id) {
        $(`#ft-${id}`).remove();
    }

    scripts.push(function () {
        $('#update').on('submit', function (e) {
            e.preventDefault();

            var alert = $('.alert');
            var button = $('.btn-primary');

            alert.hide();
            button.html('Salvando...');
            button.prop('disabled', true);

            console.log($(this).serialize());

            $.ajax({
                url: '/admin/servicos/actions/edit',
                method: 'POST',
                data: $(this).serialize(),
                complete: function (result) {
                    var data = result.responseJSON;

                    if(data.success) {
                        location.reload();
                    }else{
                        alert.fadeIn().html(data.message);
                    }

                    button.html('Salvar');
                    button.prop('disabled', false);
                }
            });

            return false;
        });
    });
</script>