<section class="features">
    <div class="container">
        <div class="h2 font-weight-bold mt-3">Por que PremiumHosting?</div>
        <div class="h5 mb-3 font-weight-normal">Simples! Olha só esses motivos...</div>
        <div class="row">
            <div class="col-md-4">
                <div class="feature">
                    <div class="icon">
                        <i class="fas fa-box-open"></i>
                    </div>
                    <div class="title">Uptime garantido</div>
                    <div class="description">
                        A disponibilidade do seu serviço é uma de nossas prioridades por isso conte com o melhor.
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="feature">
                    <div class="icon">
                        <i class="fas fa-hand-holding-usd"></i>
                    </div>
                    <div class="title">Preço flexível</div>
                    <div class="description">
                        Valorizamos a qualidade dos serviços e o custo benefício em primeiro lugar.
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="feature">
                    <div class="icon">
                        <i class="far fa-life-ring"></i>
                    </div>
                    <div class="title">Suporte ligeiro</div>
                    <div class="description">
                        Nossa equipe de suporte está sempre disponível para lhe auxiliar.
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="feature">
                    <div class="icon">
                        <i class="fas fa-truck-loading"></i>
                    </div>
                    <div class="title">Painel de controle</div>
                    <div class="description">
                        Nossos serviços contam com um painel de controle com diversas funções para facilitar.
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="feature">
                    <div class="icon">
                        <i class="fas fa-fingerprint"></i>
                    </div>
                    <div class="title">Criptografia ponta-a-ponta</div>
                    <div class="description">
                        Tomamos medidas constantes para garantir a segurança e a proteção dos seus dados.
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="feature">
                    <div class="icon">
                        <i class="fas fa-bug"></i>
                    </div>
                    <div class="title">Proteção contra DDoS</div>
                    <div class="description">
                        Os serviços são equipados com proteções anti-ddos premium de melhor qualidade.
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="py-5 bg-white">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <div class="h1 mt-5 mb-4">A solução para seus problemas!</div>
                <div class="h5 font-weight-normal text-muted">
					Nossos serviços faz com que suas cargas de trabalho com mais<br> 
					uso de processador voem porque todo o poder de<br> 
					pensamento é seu e somente seu.<br>
					Adotamos apenas o hardware mais recente e confiável,<br> 
					porque fornecer serviços de qualidade para atender à sua<br>
					satisfação é nossa principal prioridade!
            </div>
            </div>
            <div class="col-md-5">
                <img src="/app/templates/site/assets/images/share.png" class="img-fluid" alt="">
            </div>
        </div>
    </div>
</section>